# .devcontainer/Dockerfile
FROM python:latest

# Install essential packages
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y fish

