version: '3.8'

services:
  python:
    build: 
      context: ..          # Set the build context to the parent directory
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ..:/workspace:/cached
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Number of GPUs
              capabilities: [gpu]
    command: sleep infinity
    ports:
      - "11434:11434"
    profiles:
      - python

volumes:
  ollama_data:
  # python2:
  #   build: 
  #     context: .
  #     dockerfile: dockerfile
  #   volumes:
  #     - ..:/workspace:/cached
  #   command: sleep infinity
  #   profiles:
  #     - python2