# .devcontainer/Dockerfile
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

# Install essential packages
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*
    
RUN apt-get update && apt-get install -y fish
WORKDIR /workspace
COPY ../requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
RUN curl -fsSL https://ollama.com/install.sh | sh
COPY . spectra
# RUN pip install --no-cache-dir -r requirements.txt
