# .devcontainer/Dockerfile
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

# Install essential packages
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y fish

